#GET --> per richiesta, 
#POST --> per inserimento, 
#PUT --> modifica tramite replace, 
#PATCH --> per gli aggiornamenti di differenza, 
#DELETE --> per eliminare

@id = 1

# ELENCO DEGLI EVENTI
GET http://localhost:3006/events HTTP/1.1

###

# SINGOLO EVENTO
GET http://localhost:3006/events/{{id}} HTTP/1.1

###

# ELENCO DEGLI TRACKS
GET http://localhost:3006/tracks HTTP/1.1

###

# SINGOLO TRACK
GET http://localhost:3006/tracks/{{id}} HTTP/1.1

###

# ELENCO DEGLI SPEAKERS
GET http://localhost:3006/speakers HTTP/1.1

###

# SINGOLO SPEAKER
GET http://localhost:3006/speakers/{{id}} HTTP/1.1

###